server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:11111}

  application:
    name: account-service

  data:
    cassandra:
      username: cassandra # Cassandra Docker container içinde etc/cassandra/cassandra.yaml dosyasında authenticator parametresini PasswordAuthenticator olarak değiştirdik. Böylelikle username ve passwordü kullanarak bağlandık.
      password: cassandra # Cassandra Docker container içinde etc/cassandra/cassandra.yaml dosyasında authenticator parametresini PasswordAuthenticator olarak değiştirdik. Böylelikle username ve passwordü kullanarak bağlandık.
      keyspace-name: springcloud
      schema-action: create-if-not-exists
      port: 1568
      contact-points:
        - localhost
      local-datacenter: datacenter1

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9999}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"