server:
  port: 9999

spring:
  application:
    name: eureka-server

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9999}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
